apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: cluster-config
spec:
  interval: 30m
  url: https://marvin-garcia.github.io/aks-playground/